"""initial schema

Revision ID: ce5a5fe548ab
Revises: 
Create Date: 2026-09-09 23:31:01.147024
"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

import app.database.types as sa_types  # custom column types

revision: str = 'ce5a5fe548ab'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('metrics_fetched_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_channel_platform_external')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channels_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_channels_external_id'), ['external_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('keywords', sa_types.JSONB(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('last_seen_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('region', sa.String(length=8), nullable=True),
    sa.Column('history', sa_types.JSONB(), nullable=False),
    sa.Column('embedding', sa_types.Vector(), nullable=True),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_topic_slug')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=False)
        batch_op.create_index('ix_topics_trend_score', ['trend_score'], unique=False)

    op.create_table('users',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('user_id', sa_types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('platform_accounts',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('user_id', sa_types.GUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa_types.JSONB(), nullable=False),
    sa.Column('access_token_ref', sa.Text(), nullable=True),
    sa.Column('refresh_token_ref', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', 'external_account_id', name='uq_platform_account')
    )
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_accounts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('score_calibrations',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('user_id', sa_types.GUID(), nullable=False),
    sa.Column('weights', sa_types.JSONB(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('baseline_mae', sa.Float(), nullable=True),
    sa.Column('calibrated_mae', sa.Float(), nullable=True),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_calibrations', schema=None) as batch_op:
        batch_op.create_index('ix_calibration_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_calibrations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_calibrations_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('user_id', sa_types.GUID(), nullable=False),
    sa.Column('min_viral_score', sa.Float(), nullable=False),
    sa.Column('auto_approve_score', sa.Float(), nullable=False),
    sa.Column('reject_below_score', sa.Float(), nullable=False),
    sa.Column('clips_per_video', sa.Integer(), nullable=False),
    sa.Column('min_clip_seconds', sa.Float(), nullable=False),
    sa.Column('max_clip_seconds', sa.Float(), nullable=False),
    sa.Column('crop_mode', sa.String(length=32), nullable=False),
    sa.Column('caption_style', sa.String(length=32), nullable=False),
    sa.Column('caption_position', sa.String(length=32), nullable=False),
    sa.Column('caption_overrides', sa_types.JSONB(), nullable=False),
    sa.Column('output_width', sa.Integer(), nullable=False),
    sa.Column('output_height', sa.Integer(), nullable=False),
    sa.Column('output_fps', sa.Integer(), nullable=True),
    sa.Column('scoring_weights', sa_types.JSONB(), nullable=False),
    sa.Column('trend_weights', sa_types.JSONB(), nullable=False),
    sa.Column('preferred_categories', sa_types.JSONB(), nullable=False),
    sa.Column('preferred_languages', sa_types.JSONB(), nullable=False),
    sa.Column('trend_regions', sa_types.JSONB(), nullable=False),
    sa.Column('quality_threshold', sa.Float(), nullable=False),
    sa.Column('max_regeneration_attempts', sa.Integer(), nullable=False),
    sa.Column('block_on_safety_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_settings_user')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('user_id', sa_types.GUID(), nullable=False),
    sa.Column('channel_id', sa_types.GUID(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_name', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('tags', sa_types.JSONB(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('published_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('authorization_status', sa.String(length=32), nullable=False),
    sa.Column('authorization_note', sa.Text(), nullable=True),
    sa.Column('authorization_evidence_url', sa.String(length=2048), nullable=True),
    sa.Column('authorized_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('authorized_by_user_id', sa_types.GUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('video_codec', sa.String(length=64), nullable=True),
    sa.Column('audio_codec', sa.String(length=64), nullable=True),
    sa.Column('audio_available', sa.Boolean(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('trend_breakdown', sa_types.JSONB(), nullable=False),
    sa.Column('extra_metadata', sa_types.JSONB(), nullable=False),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_video_user_source_external')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_authorization_status'), ['authorization_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_status'), ['status'], unique=False)
        batch_op.create_index('ix_videos_trend_score', ['trend_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_videos_user_status', ['user_id', 'status'], unique=False)

    op.create_table('candidate_clips',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('video_id', sa_types.GUID(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('context_lead_in', sa.Float(), nullable=False),
    sa.Column('raw_moment_start', sa.Float(), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('transcript_excerpt', sa.Text(), nullable=True),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa_types.JSONB(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duplicate_of_id', sa_types.GUID(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('embedding', sa_types.Vector(), nullable=True),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['candidate_clips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_clips_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_clips_video_id'), ['video_id'], unique=False)
        batch_op.create_index('ix_candidates_status', ['status'], unique=False)
        batch_op.create_index('ix_candidates_video_score', ['video_id', 'viral_score'], unique=False)

    op.create_table('scenes',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('video_id', sa_types.GUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('change_score', sa.Float(), nullable=True),
    sa.Column('face_summary', sa_types.JSONB(), nullable=False),
    sa.Column('visual_metrics', sa_types.JSONB(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index('ix_scenes_video_time', ['video_id', 'start_time'], unique=False)

    op.create_table('topic_mentions',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('topic_id', sa_types.GUID(), nullable=False),
    sa.Column('video_id', sa_types.GUID(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('matched_terms', sa_types.JSONB(), nullable=False),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'video_id', name='uq_mention_topic_video')
    )
    with op.batch_alter_table('topic_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_mentions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_mentions_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_mentions_video_id'), ['video_id'], unique=False)

    op.create_table('transcripts',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('video_id', sa_types.GUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('language_confidence', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provider_metadata', sa_types.JSONB(), nullable=False),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', name='uq_transcript_video')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcripts_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcripts_video_id'), ['video_id'], unique=False)

    op.create_table('video_metrics',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('video_id', sa_types.GUID(), nullable=False),
    sa.Column('captured_at', sa_types.UTCDateTime(), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('view_velocity', sa.Float(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('comment_rate', sa.Float(), nullable=True),
    sa.Column('growth_acceleration', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_video_metrics_video_time', ['video_id', 'captured_at'], unique=False)

    op.create_table('generated_clips',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('user_id', sa_types.GUID(), nullable=False),
    sa.Column('video_id', sa_types.GUID(), nullable=False),
    sa.Column('candidate_id', sa_types.GUID(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('crop_mode', sa.String(length=32), nullable=False),
    sa.Column('caption_style', sa.String(length=32), nullable=False),
    sa.Column('caption_position', sa.String(length=32), nullable=False),
    sa.Column('render_config', sa_types.JSONB(), nullable=False),
    sa.Column('crop_keyframes', sa_types.JSONB(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('hook_text', sa.Text(), nullable=True),
    sa.Column('hook_alternatives', sa_types.JSONB(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instagram_caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa_types.JSONB(), nullable=False),
    sa.Column('keywords', sa_types.JSONB(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('captions', sa_types.JSONB(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('subtitle_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=True),
    sa.Column('viral_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('safety_verdict', sa.String(length=16), nullable=True),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('rejected_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('publish_status', sa.String(length=32), nullable=False),
    sa.Column('embedding', sa_types.Vector(), nullable=True),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_clips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_clips', schema=None) as batch_op:
        batch_op.create_index('ix_clips_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('ix_clips_video', ['video_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_clips_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_clips_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_clips_perceptual_hash'), ['perceptual_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_clips_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_clips_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_clips_viral_score'), ['viral_score'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('transcript_id', sa_types.GUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker', sa.String(length=64), nullable=True),
    sa.Column('words', sa_types.JSONB(), nullable=False),
    sa.Column('words_per_second', sa.Float(), nullable=True),
    sa.Column('leading_pause', sa.Float(), nullable=True),
    sa.Column('trailing_pause', sa.Float(), nullable=True),
    sa.Column('prefilter_score', sa.Float(), nullable=True),
    sa.Column('signals', sa_types.JSONB(), nullable=False),
    sa.Column('embedding', sa_types.Vector(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('ix_segments_time', ['transcript_id', 'start_time'], unique=False)
        batch_op.create_index('ix_segments_transcript_index', ['transcript_id', 'index'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_prefilter_score'), ['prefilter_score'], unique=False)

    op.create_table('clip_analytics',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('clip_id', sa_types.GUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('captured_at', sa_types.UTCDateTime(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('saves', sa.BigInteger(), nullable=True),
    sa.Column('average_view_duration', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('retention_curve', sa_types.JSONB(), nullable=False),
    sa.Column('performance_percentile', sa.Float(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('prediction_error', sa.Float(), nullable=True),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['generated_clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clip_id', 'platform', 'captured_at', name='uq_analytics_clip_platform_time')
    )
    with op.batch_alter_table('clip_analytics', schema=None) as batch_op:
        batch_op.create_index('ix_analytics_clip_time', ['clip_id', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clip_analytics_created_at'), ['created_at'], unique=False)

    op.create_table('clip_variants',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('clip_id', sa_types.GUID(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('crop_mode', sa.String(length=32), nullable=False),
    sa.Column('caption_style', sa.String(length=32), nullable=False),
    sa.Column('hook_text', sa.Text(), nullable=True),
    sa.Column('render_config', sa_types.JSONB(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['generated_clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clip_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clip_variants_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_variants_clip_label', ['clip_id', 'label'], unique=False)

    op.create_table('content_safety_checks',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('clip_id', sa_types.GUID(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('category_scores', sa_types.JSONB(), nullable=False),
    sa.Column('flagged_categories', sa_types.JSONB(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence', sa_types.JSONB(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['generated_clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_safety_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_safety_checks_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_safety_clip', ['clip_id', 'created_at'], unique=False)

    op.create_table('media_assets',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('video_id', sa_types.GUID(), nullable=True),
    sa.Column('clip_id', sa_types.GUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('extra', sa_types.JSONB(), nullable=False),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['generated_clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_clip_id'), ['clip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_video_id'), ['video_id'], unique=False)
        batch_op.create_index('ix_media_assets_video_kind', ['video_id', 'kind'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('user_id', sa_types.GUID(), nullable=False),
    sa.Column('video_id', sa_types.GUID(), nullable=True),
    sa.Column('clip_id', sa_types.GUID(), nullable=True),
    sa.Column('parent_job_id', sa_types.GUID(), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('celery_task_id', sa.String(length=128), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('payload', sa_types.JSONB(), nullable=False),
    sa.Column('result', sa_types.JSONB(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa_types.JSONB(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('started_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('finished_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('llm_input_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_output_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['generated_clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_job_id'], ['processing_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_type_status', ['job_type', 'status'], unique=False)
        batch_op.create_index('ix_jobs_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('ix_jobs_video', ['video_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_celery_task_id'), ['celery_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('publishing_jobs',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('clip_id', sa_types.GUID(), nullable=False),
    sa.Column('account_id', sa_types.GUID(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_for', sa_types.UTCDateTime(), nullable=True),
    sa.Column('published_at', sa_types.UTCDateTime(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hashtags', sa_types.JSONB(), nullable=False),
    sa.Column('privacy', sa.String(length=32), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('response_payload', sa_types.JSONB(), nullable=False),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clip_id'], ['generated_clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publishing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publishing_jobs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publishing_jobs_clip_id'), ['clip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publishing_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publishing_jobs_external_post_id'), ['external_post_id'], unique=False)
        batch_op.create_index('ix_publishing_status_scheduled', ['status', 'scheduled_for'], unique=False)

    op.create_table('quality_checks',
    sa.Column('id', sa_types.GUID(), nullable=False),
    sa.Column('clip_id', sa_types.GUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('issues', sa_types.JSONB(), nullable=False),
    sa.Column('recommendations', sa_types.JSONB(), nullable=False),
    sa.Column('technical', sa_types.JSONB(), nullable=False),
    sa.Column('auto_corrected', sa.Boolean(), nullable=False),
    sa.Column('correction_applied', sa.Text(), nullable=True),
    sa.Column('created_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa_types.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['generated_clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_checks_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_quality_clip_attempt', ['clip_id', 'attempt'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_quality_clip_attempt')
        batch_op.drop_index(batch_op.f('ix_quality_checks_created_at'))

    op.drop_table('quality_checks')
    with op.batch_alter_table('publishing_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_publishing_status_scheduled')
        batch_op.drop_index(batch_op.f('ix_publishing_jobs_external_post_id'))
        batch_op.drop_index(batch_op.f('ix_publishing_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_publishing_jobs_clip_id'))
        batch_op.drop_index(batch_op.f('ix_publishing_jobs_account_id'))

    op.drop_table('publishing_jobs')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_celery_task_id'))
        batch_op.drop_index('ix_jobs_video')
        batch_op.drop_index('ix_jobs_user_status')
        batch_op.drop_index('ix_jobs_type_status')

    op.drop_table('processing_jobs')
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_media_assets_video_kind')
        batch_op.drop_index(batch_op.f('ix_media_assets_video_id'))
        batch_op.drop_index(batch_op.f('ix_media_assets_created_at'))
        batch_op.drop_index(batch_op.f('ix_media_assets_clip_id'))

    op.drop_table('media_assets')
    with op.batch_alter_table('content_safety_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_safety_clip')
        batch_op.drop_index(batch_op.f('ix_content_safety_checks_created_at'))

    op.drop_table('content_safety_checks')
    with op.batch_alter_table('clip_variants', schema=None) as batch_op:
        batch_op.drop_index('ix_variants_clip_label')
        batch_op.drop_index(batch_op.f('ix_clip_variants_created_at'))

    op.drop_table('clip_variants')
    with op.batch_alter_table('clip_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_analytics_created_at'))
        batch_op.drop_index('ix_analytics_clip_time')

    op.drop_table('clip_analytics')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_prefilter_score'))
        batch_op.drop_index('ix_segments_transcript_index')
        batch_op.drop_index('ix_segments_time')

    op.drop_table('transcript_segments')
    with op.batch_alter_table('generated_clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_clips_viral_score'))
        batch_op.drop_index(batch_op.f('ix_generated_clips_user_id'))
        batch_op.drop_index(batch_op.f('ix_generated_clips_status'))
        batch_op.drop_index(batch_op.f('ix_generated_clips_perceptual_hash'))
        batch_op.drop_index(batch_op.f('ix_generated_clips_created_at'))
        batch_op.drop_index(batch_op.f('ix_generated_clips_candidate_id'))
        batch_op.drop_index('ix_clips_video')
        batch_op.drop_index('ix_clips_user_status')

    op.drop_table('generated_clips')
    with op.batch_alter_table('video_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_video_metrics_video_time')

    op.drop_table('video_metrics')
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_video_id'))
        batch_op.drop_index(batch_op.f('ix_transcripts_language'))
        batch_op.drop_index(batch_op.f('ix_transcripts_created_at'))

    op.drop_table('transcripts')
    with op.batch_alter_table('topic_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_mentions_video_id'))
        batch_op.drop_index(batch_op.f('ix_topic_mentions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topic_mentions_created_at'))

    op.drop_table('topic_mentions')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index('ix_scenes_video_time')

    op.drop_table('scenes')
    with op.batch_alter_table('candidate_clips', schema=None) as batch_op:
        batch_op.drop_index('ix_candidates_video_score')
        batch_op.drop_index('ix_candidates_status')
        batch_op.drop_index(batch_op.f('ix_candidate_clips_video_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_clips_created_at'))

    op.drop_table('candidate_clips')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index('ix_videos_user_status')
        batch_op.drop_index(batch_op.f('ix_videos_user_id'))
        batch_op.drop_index('ix_videos_trend_score')
        batch_op.drop_index(batch_op.f('ix_videos_status'))
        batch_op.drop_index(batch_op.f('ix_videos_published_at'))
        batch_op.drop_index(batch_op.f('ix_videos_external_id'))
        batch_op.drop_index(batch_op.f('ix_videos_created_at'))
        batch_op.drop_index(batch_op.f('ix_videos_content_hash'))
        batch_op.drop_index(batch_op.f('ix_videos_channel_id'))
        batch_op.drop_index(batch_op.f('ix_videos_category'))
        batch_op.drop_index(batch_op.f('ix_videos_authorization_status'))

    op.drop_table('videos')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_settings_created_at'))

    op.drop_table('user_settings')
    with op.batch_alter_table('score_calibrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_calibrations_user_id'))
        batch_op.drop_index(batch_op.f('ix_score_calibrations_created_at'))
        batch_op.drop_index('ix_calibration_user_active')

    op.drop_table('score_calibrations')
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_platform_accounts_created_at'))

    op.drop_table('platform_accounts')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_created_at'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index('ix_topics_trend_score')
        batch_op.drop_index(batch_op.f('ix_topics_slug'))
        batch_op.drop_index(batch_op.f('ix_topics_region'))
        batch_op.drop_index(batch_op.f('ix_topics_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_topics_created_at'))

    op.drop_table('topics')
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channels_external_id'))
        batch_op.drop_index(batch_op.f('ix_channels_created_at'))

    op.drop_table('channels')
    # ### end Alembic commands ###
