#!/usr/bin/env python3
"""Seed a running instance with a demo video, transcript and clip.

Exercises the same public API the dashboard uses, so it doubles as a smoke
test of a deployment:

    python scripts/seed_demo.py --email demo@example.com --password ...

The sample video is synthetic (``scripts/make_sample_video.py``) and the
transcript is planted as a sidecar, so no third-party content is involved and
no transcription model is required.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import httpx

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "backend"))

TRANSCRIPT = """\
Okay so welcome back to the channel, please subscribe before we start.
Most people completely misunderstand how compounding works. They think it is \
about patience. It is not. It is about survival.
The reason is simple. Compounding only works if you never interrupt it, and \
almost everyone interrupts it. One bad year of panic selling erases nine good \
years of returns.
So what do you actually do? You automate the decision once, and then you stop \
touching it. That is the whole strategy.
Anyway that is basically all I wanted to say about that today.
"""


def wait_for_job(client: httpx.Client, base: str, job_id: str, timeout: int = 900) -> dict:
    deadline = time.monotonic() + timeout
    last_stage = None
    while time.monotonic() < deadline:
        job = client.get(f"{base}/api/v1/jobs/{job_id}").json()
        if job.get("stage") and job["stage"] != last_stage:
            last_stage = job["stage"]
            print(f"    {job['status'].lower()}: {last_stage}")
        if job["status"] in ("COMPLETED", "FAILED", "CANCELLED"):
            return job
        time.sleep(2)
    raise TimeoutError(f"Job {job_id} did not finish within {timeout}s")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", default="http://127.0.0.1:8000")
    parser.add_argument("--email", default="demo@example.com")
    parser.add_argument("--password", default="demo-password-123")
    parser.add_argument(
        "--video",
        type=Path,
        default=REPO / "data" / "samples" / "sample_landscape.mp4",
    )
    args = parser.parse_args()

    if not args.video.exists():
        print(
            f"Sample video not found at {args.video}.\n"
            "Run: python scripts/make_sample_video.py",
            file=sys.stderr,
        )
        return 1

    base = args.base.rstrip("/")
    with httpx.Client(timeout=300.0) as client:
        # 1. Account
        response = client.post(
            f"{base}/api/v1/auth/register",
            json={"email": args.email, "password": args.password, "full_name": "Demo"},
        )
        if response.status_code == 409:
            response = client.post(
                f"{base}/api/v1/auth/login",
                json={"email": args.email, "password": args.password},
            )
        response.raise_for_status()
        client.headers["Authorization"] = f"Bearer {response.json()['access_token']}"
        print(f"[1/6] signed in as {args.email}")

        # 2. Register the video, asserting ownership
        video = client.post(
            f"{base}/api/v1/videos",
            json={
                "title": "How compounding actually works",
                "source": "UPLOAD",
                "creator_name": "Demo Creator",
                "category": "Education",
                "language": "en",
                "authorization_status": "USER_OWNED",
                "authorization_note": "Synthetic sample generated by this repository.",
            },
        )
        video.raise_for_status()
        video_id = video.json()["id"]
        print(f"[2/6] registered video {video_id}")

        # 3. Upload the media
        with args.video.open("rb") as handle:
            upload = client.post(
                f"{base}/api/v1/videos/{video_id}/upload",
                files={"file": (args.video.name, handle, "video/mp4")},
            )
        upload.raise_for_status()
        print(f"[3/6] uploaded {args.video.name}")

        # 4. Plant the transcript sidecar the mock provider reads
        from tests.fixtures.transcripts import build_transcript  # noqa: E402
        from app.services.storage_paths import video_workdir  # noqa: E402

        transcript = build_transcript(TRANSCRIPT)
        sidecar = video_workdir(video_id) / "audio.transcript.json"
        sidecar.write_text(
            json.dumps(
                {
                    "language": transcript.language,
                    "duration": transcript.duration,
                    "segments": [
                        {
                            "start": chunk.start,
                            "end": chunk.end,
                            "text": chunk.text,
                            "words": [w.to_dict() for w in chunk.words],
                        }
                        for chunk in transcript.chunks
                    ],
                }
            ),
            encoding="utf-8",
        )
        print(f"[4/6] planted transcript sidecar at {sidecar}")

        # 5. Analyse
        job = client.post(
            f"{base}/api/v1/videos/{video_id}/analyze", json={"force": True}
        )
        job.raise_for_status()
        result = wait_for_job(client, base, job.json()["job_id"])
        if result["status"] != "COMPLETED":
            print(f"    analysis failed: {result['error_message']}", file=sys.stderr)
            return 1
        print(
            f"[5/6] analysed: {result['result']['segments']} segments, "
            f"{result['result']['candidates']} candidates"
        )

        # 6. Render the top candidate
        candidates = client.get(f"{base}/api/v1/videos/{video_id}/candidates").json()
        if not candidates:
            print("    no candidates were produced", file=sys.stderr)
            return 1
        generate = client.post(
            f"{base}/api/v1/clips/generate",
            json={"video_id": video_id, "candidate_ids": [candidates[0]["id"]]},
        )
        generate.raise_for_status()
        result = wait_for_job(client, base, generate.json()["job_id"])
        if result["status"] != "COMPLETED":
            print(f"    clip generation failed: {result['error_message']}", file=sys.stderr)
            return 1

        clip_ids = result["result"].get("clips") or []
        print(f"[6/6] generated {len(clip_ids)} clip(s)")
        for clip_id in clip_ids:
            clip = client.get(f"{base}/api/v1/clips/{clip_id}").json()
            print(
                f"    {clip['width']}x{clip['height']} "
                f"{clip['duration_seconds']:.1f}s "
                f"viral={clip['viral_score']:.0f} "
                f"quality={clip['quality_score']:.0f} "
                f"safety={clip['safety_verdict']} "
                f"status={clip['status']}"
            )
    print("\nDone. Open the dashboard to review the clip.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
